project:
  type: website
  output-dir: docs

website:
  title: "CS 152: Neural Networks"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: calendar/calendar.qmd
        text: Calendar
      - href: https://github.com/orgs/CS152-Neural-Networks-Fall-2023/repositories
        text: Homeworks
      - href: https://harveymuddcollege.instructure.com/courses/615/
        text: Canvas
      - href: https://github.com/orgs/CS152-Neural-Networks-Fall-2023/
        text: Github


format:
  html:
    theme: 
      - cosmo
      - theme.scss
    toc: true