project:
  type: website
  output-dir: docs

website:
  title: "CS 152: Neural Networks"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: calendar/calendar.qmd
        text: Calendar
      - href: https://github.com/orgs/CS152-Neural-Networks-Fall-2023/repositories
        text: Homeworks
      - href: assignments/final-project/outline.qmd
        text: Project
      - href: https://github.com/orgs/CS152/
        text: Github
      - href: https://www.gradescope.com/courses/710173
        text: Gradescope


format:
  html:
    theme: 
      - cosmo
      - theme.scss
    toc: true