---
title: "Course Calendar"
---

+---------+---------+------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Lecture | Date    | Topics                                                     | Textbook                                                                                                                    | Materials                                                                                         | Homework                                                                                                                                                                   |
+=========+=========+============================================================+=============================================================================================================================+===================================================================================================+============================================================================================================================================================================+
| 1       | 1/17    | Course introduction, prediction models                     | [Book 1](https://probml.github.io/pml-book/book1.html): 1.2.1-1.2.2, 7.1.1-7.2.4, 7.8.1, 7.8.2                              | [Notes](../lecture1-background/notes.qmd)                                                         | Homework 1 assigned ([Drive](https://drive.google.com/drive/folders/15i-IPTRAdyTaqx6iutt376numH-rxLnn?usp=drive_link)) **Due: 1/25 11:59pm**                               |
|         |         |                                                            |                                                                                                                             |                                                                                                   |                                                                                                                                                                            |
|         |         |                                                            |                                                                                                                             |                                                                                                   | [Solutions](https://nbviewer.org/urls/gist.githubusercontent.com/gabehope/516837c351149d3de9c1a29839000273/raw/182d169ba83cb3a6d8539a2297f068dce7834ab1/solutions.ipynb)   |
+---------+---------+------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 2       | 1/22    | Linear regression, Gradient descent                        | [Book 1](https://probml.github.io/pml-book/book1.html): 4.2.1, 4.2.2, 11.1-11.2.4                                           | [Notes](../lecture2-linear-regression/notes.qmd)                                                  |                                                                                                                                                                            |
|         |         |                                                            |                                                                                                                             |                                                                                                   |                                                                                                                                                                            |
|         |         |                                                            |                                                                                                                             | [Slides](./notes/lecture1.pdf)                                                                    |                                                                                                                                                                            |
+---------+---------+------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 3       | 1/24    | Linear regression, maximum likelihood                      | [Book 1](https://probml.github.io/pml-book/book1.html): 4.2.1, 4.2.2, 11.1-11.2.4                                           | [Notes](../lecture2-linear-regression/notes.qmd)                                                  | Homework 2 assigned ([Drive](https://drive.google.com/drive/folders/1deohwJarw4aa-Te3DYDrdbn35v1EWIsm?usp=drive_link), [hints](../misc/hw2-hint.qmd)) **Due: 2/1 11:59pm** |
|         |         |                                                            |                                                                                                                             |                                                                                                   |                                                                                                                                                                            |
|         |         |                                                            |                                                                                                                             | [Slides](./notes/lecture2.pdf)                                                                    | [Solutions](https://nbviewer.org/urls/gist.githubusercontent.com/gabehope/4bf759748a9fd313137d9fbeadd1ce85/raw/18303a4055fa37b974daebc8d7078b83bf019f7a/solutions.ipynb)   |
+---------+---------+------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 4       | 1/29    | Logistic regression                                        | [Book 1](https://probml.github.io/pml-book/book1.html): 10.1, 10.2.1, 10.2.3, 10.3.1-10.3.3                                 | [Notes](../lecture3-logistic-regression/notes.qmd)                                                |                                                                                                                                                                            |
|         |         |                                                            |                                                                                                                             |                                                                                                   |                                                                                                                                                                            |
|         |         |                                                            |                                                                                                                             | [Slides](./notes/lecture3.pdf)                                                                    |                                                                                                                                                                            |
+---------+---------+------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 5       | 1/31    | Logistic regression                                        | [Book 1](https://probml.github.io/pml-book/book1.html): 10.1, 10.2.1, 10.2.3, 10.3.1-10.3.3                                 | [Notes](../lecture3-logistic-regression/notes.qmd)                                                | Final project ethics warm-up assigned ([Description](../assignments/final-project/ethics.qmd)) **Due: 2/8 11:59pm**                                                        |
|         |         |                                                            |                                                                                                                             |                                                                                                   |                                                                                                                                                                            |
|         |         |                                                            |                                                                                                                             | [Slides](./notes/lecture4.pdf)                                                                    |                                                                                                                                                                            |
|         |         |                                                            |                                                                                                                             |                                                                                                   |                                                                                                                                                                            |
|         |         |                                                            |                                                                                                                             | [Notebook](https://colab.research.google.com/drive/1MlFAWYkgI58xjxTYWKJoSdU64xRObyaq?usp=sharing) |                                                                                                                                                                            |
+---------+---------+------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 6       | 2/5     | Multinomial logistic regression                            | [Book 1](https://probml.github.io/pml-book/book1.html): 10.2.2                                                              | [Notes](../lecture4-feature-transforms/notes.qmd)                                                 |                                                                                                                                                                            |
|         |         |                                                            |                                                                                                                             |                                                                                                   |                                                                                                                                                                            |
|         |         |                                                            |                                                                                                                             | [Slides](./notes/lecture5.pdf)                                                                    |                                                                                                                                                                            |
+---------+---------+------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 7       | 2/7     | Feature transforms                                         | [Book 1](https://probml.github.io/pml-book/book1.html): 13.1, 13.2                                                          | [Notes](../lecture4-feature-transforms/notes.qmd)                                                 | Homework 3 assigned ([Drive](https://drive.google.com/drive/folders/1Df96GdFpucM-YUf6c5PTWUfxWY-UrLXl?usp=drive_link)) **Due: 2/15 11:59pm**                               |
|         |         |                                                            |                                                                                                                             |                                                                                                   |                                                                                                                                                                            |
|         |         |                                                            |                                                                                                                             | [Slides](./notes/lecture6.pdf)                                                                    | [Solutions](https://nbviewer.org/urls/gist.githubusercontent.com/gabehope/adaba97e7b81ab58551a57dbf84e9927/raw/8946f77a588a7f5be7f3369b5a2c9fc7ccdde74d/solutions.ipynb)   |
+---------+---------+------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 8       | 2/12    | Neural networks                                            | [Book 1](https://probml.github.io/pml-book/book1.html): 13.1, 13.2                                                          | [Notebook](https://colab.research.google.com/drive/1MlFAWYkgI58xjxTYWKJoSdU64xRObyaq?usp=sharing) |                                                                                                                                                                            |
|         |         |                                                            |                                                                                                                             |                                                                                                   |                                                                                                                                                                            |
|         |         |                                                            |                                                                                                                             | [Slides](./notes/lecture6.pdf)                                                                    |                                                                                                                                                                            |
+---------+---------+------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 9       | 2/14    | Neural networks (cont.)                                    | [Book 1](https://probml.github.io/pml-book/book1.html): 13.1, 13.2                                                          | [Notes](../lecture5-neural-networks-intro/notes.qmd)                                              | Homework 4 assigned ([Drive](https://drive.google.com/drive/folders/1wIblhOu4c0LlbiveKP1Z2uTVre3d62pO?usp=drive_link)) **Due: 2/23 11:59pm**                               |
|         |         |                                                            |                                                                                                                             |                                                                                                   |                                                                                                                                                                            |
|         |         |                                                            |                                                                                                                             | [Slides](./notes/lecture7.pdf)                                                                    | [Solutions](https://nbviewer.org/urls/gist.githubusercontent.com/gabehope/c2f9e6f1dcd330e0b0e96df0a6152cf1/raw/400b92a607baaafc25604b4e7ed9820e1e38d972/solutions.ipynb)   |
+---------+---------+------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 10      | 2/19    | Automatic Differentiation                                  | [Book 1](https://probml.github.io/pml-book/book1.html): 13.3                                                                | [Notes](../lecture6-backpropagation/notes.qmd)                                                    |                                                                                                                                                                            |
|         |         |                                                            |                                                                                                                             |                                                                                                   |                                                                                                                                                                            |
|         |         |                                                            |                                                                                                                             | [Slides](./notes/lecture8.pdf)                                                                    |                                                                                                                                                                            |
+---------+---------+------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 11      | 2/21    | Reverse-mode Automatic Differentiation                     | [Book 1](https://probml.github.io/pml-book/book1.html): 13.3                                                                | [Notes](../lecture6-backpropagation/notes.qmd)                                                    |                                                                                                                                                                            |
|         |         |                                                            |                                                                                                                             |                                                                                                   |                                                                                                                                                                            |
|         |         |                                                            |                                                                                                                             | [Slides](./notes/lecture10.pdf)                                                                   |                                                                                                                                                                            |
+---------+---------+------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 12      | 2/26    | Reverse-mode Automatic Differentiation (cont.)             | [Book 1](https://probml.github.io/pml-book/book1.html): 13.4.5, 13.5                                                        | [Notes](../lecture6-backpropagation/notes.qmd)                                                    |                                                                                                                                                                            |
|         |         |                                                            |                                                                                                                             |                                                                                                   |                                                                                                                                                                            |
|         |         |                                                            |                                                                                                                             | [Slides](./notes/lecture10.pdf)                                                                   |                                                                                                                                                                            |
+---------+---------+------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 13      | 2/28    | PyTorch                                                    | [Book 1](https://probml.github.io/pml-book/book1.html): 13.5                                                                | [Notebook](https://drive.google.com/file/d/1N76hpENuKchbfN0o-NZ02FAgZYPiWPVf/view?usp=drive_link) | Homework 5 assigned ([Drive](https://drive.google.com/drive/folders/1C9vFAnO_sogGupxvOrU4uQl8ZkF7seU5?usp=drive_link)) (**Due: 3/7 11:59pm**                               |
+---------+---------+------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 14      | 3/4     | Initialization, L1 & L2 regularization                     | [Book 1](https://probml.github.io/pml-book/book1.html): 8.4                                                                 |                                                                                                   |                                                                                                                                                                            |
+---------+---------+------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 15      | 3/6     | Regularization (Cont.), Dropout                            | [Book 1](https://probml.github.io/pml-book/book1.html): 8.4                                                                 |                                                                                                   | Homework 6 assigned **Due: 3/21 11:59pm**                                                                                                                                  |
+---------+---------+------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|         | 3/11    | No class (Spring break)                                    |                                                                                                                             |                                                                                                   |                                                                                                                                                                            |
+---------+---------+------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|         | 3/13    | No class (Spring break)                                    |                                                                                                                             |                                                                                                   |                                                                                                                                                                            |
+---------+---------+------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 16      | 3/18    | Normalization                                              | [Book 1](https://probml.github.io/pml-book/book1.html): 13.4.1-13.4.2, 14.2.4                                               |                                                                                                   | Final project proposal assigned ([Description](../assignments/final-project/outline.qmd)) **Due: 3/25 11:59pm**                                                            |
+---------+---------+------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 17      | 3/20    | Residual networks                                          | [Book 1](https://probml.github.io/pml-book/book1.html): 13.4.3-13.4.5                                                       |                                                                                                   | Homework 7 assigned **Due: 3/28 11:59pm**                                                                                                                                  |
+---------+---------+------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 18      | 3/25    | Neural networks for images, convolutional layers           | [Book 1](https://probml.github.io/pml-book/book1.html): 14.1-14.3                                                           |                                                                                                   |                                                                                                                                                                            |
+---------+---------+------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 19      | 3/27    | Convolutional networks (cont.)                             | [Book 1](https://probml.github.io/pml-book/book1.html): 14.1-14.3                                                           |                                                                                                   | Homework 8 assigned **Due: 4/4 11:59pm**                                                                                                                                   |
+---------+---------+------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 20      | 4/1     | Convolutional architectures                                | [Book 1](https://probml.github.io/pml-book/book1.html): 14.1-14.3                                                           |                                                                                                   |                                                                                                                                                                            |
+---------+---------+------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 21      | 4/3     | Recurrent networks                                         | [Book 1](https://probml.github.io/pml-book/book1.html): 15.1, 15.2.1-15.2.3                                                 |                                                                                                   | Homework 9 assigned **Due: 4/11 11:59pm**                                                                                                                                  |
+---------+---------+------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 22      | 4/8     | Language models, LSTMs                                     | [Book 1](https://probml.github.io/pml-book/book1.html): 15.2.5-15.2.7                                                       |                                                                                                   |                                                                                                                                                                            |
+---------+---------+------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 23      | 4/10    | Attention layers                                           | [Book 1](https://probml.github.io/pml-book/book1.html): 15.2.1-15.2.6                                                       |                                                                                                   | Homework 10 assigned **Due: 4/18 11:59pm**                                                                                                                                 |
+---------+---------+------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 24      | 4/15    | Transformers                                               | [Book 1](https://probml.github.io/pml-book/book1.html): 15.2.1-15.2.6, <http://nlp.seas.harvard.edu/annotated-transformer/> |                                                                                                   |                                                                                                                                                                            |
+---------+---------+------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 25      | 4/17    | Transformers (cont.), Large language models                | [Book 1](https://probml.github.io/pml-book/book1.html): 15.4.1, 15.4.2-15.4.6                                               |                                                                                                   | Final project check-in assigned ([Description](../assignments/final-project/outline.qmd)) **Due: 4/22 11:59pm**                                                            |
+---------+---------+------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 26      | 4/22    | GPUs, TPUs and energy usage (Time permitting)              | [Book 1](https://probml.github.io/pml-book/book1.html): 15.4.1, 15.4.2-15.4.6                                               |                                                                                                   |                                                                                                                                                                            |
+---------+---------+------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 27      | 4/24    | Addressing the biases of neural networks (Time permitting) |                                                                                                                             |                                                                                                   |                                                                                                                                                                            |
+---------+---------+------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|         | 5/3     |                                                            |                                                                                                                             |                                                                                                   | **Final Project Due (11:59pm)**                                                                                                                                            |
|         |         |                                                            |                                                                                                                             |                                                                                                   |                                                                                                                                                                            |
|         |         |                                                            |                                                                                                                             |                                                                                                   | ([Description](../assignments/final-project/outline.qmd))                                                                                                                  |
+---------+---------+------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------+